# Generated by Django 5.2 on 2025-04-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('ec_admin', 'EC Admin')], default='ec_admin', max_length=30),
        ),
    ]
